2020-01-14 10:14:54 INFO:A_2.py:29 Setting Workflow basic metadata 

2020-01-14 10:14:54 INFO:A_2.py:90 Workflow initialization 

2020-01-14 10:14:54 DEBUG:PyroUtil.py:176 Can connect to a LISTENING port of nameserver on 172.30.0.1:9090 

2020-01-14 10:14:54 DEBUG:PyroUtil.py:188 Connected to NameServer on 172.30.0.1:9090. Pyro4 version on your localhost is 4.77 

2020-01-14 10:14:54 INFO:PyroUtil.py:556 Located Job Manager eX_DigimatMF_JobManager at: 172.30.0.112 44382 None None 

2020-01-14 10:14:54 DEBUG:PyroUtil.py:252 Application eX_DigimatMF_JobManager, found URI PYRO:obj_7db04ce6dc304145b7e2367443ea6e86@172.30.0.112:44382 on ('172.30.0.112', 44382, 'None', 'None') from a nameServer <Pyro4.core.Proxy at 0x7f64160fa710; connected IPv4; for PYRO:Pyro.NameServer@172.30.0.1:9090> 

2020-01-14 10:14:54 INFO:PyroUtil.py:260 Connecting to application eX_DigimatMF_JobManager with <Pyro4.core.Proxy at 0x7f64160fabe0; not connected; for PYRO:obj_7db04ce6dc304145b7e2367443ea6e86@172.30.0.112:44382> 

2020-01-14 10:14:54 DEBUG:PyroUtil.py:262 Connected to Mupif.JobManager.SimpleJobManager2 with the application eX_DigimatMF_JobManager 

2020-01-14 10:14:54 INFO:PyroUtil.py:556 Located Job Manager MUL2.JobManager@UseCase1 at: 172.30.0.172 44389 None None 

2020-01-14 10:14:54 DEBUG:PyroUtil.py:252 Application MUL2.JobManager@UseCase1, found URI PYRO:obj_d5b2018cc46f42fd99418801bee3e2ca@172.30.0.172:44389 on ('172.30.0.172', 44389, 'None', 'None') from a nameServer <Pyro4.core.Proxy at 0x7f64160fa710; connected IPv4; for PYRO:Pyro.NameServer@172.30.0.1:9090> 

2020-01-14 10:14:54 INFO:PyroUtil.py:260 Connecting to application MUL2.JobManager@UseCase1 with <Pyro4.core.Proxy at 0x7f64160faa90; not connected; for PYRO:obj_d5b2018cc46f42fd99418801bee3e2ca@172.30.0.172:44389> 

2020-01-14 10:14:55 DEBUG:PyroUtil.py:262 Connected to Mupif.JobManager.SimpleJobManager2 with the application MUL2.JobManager@UseCase1 

2020-01-14 10:14:55 DEBUG:PyroUtil.py:597 Trying to connect to JobManager 

2020-01-14 10:14:56 INFO:PyroUtil.py:615 Allocated job, returned record from jobManager:(1, '1@eX_DigimatMF_JobManager', 9000) 

2020-01-14 10:14:56 INFO:PyroUtil.py:638 Scenario: Connecting to 1@eX_DigimatMF_JobManager 9000 

2020-01-14 10:14:56 DEBUG:PyroUtil.py:252 Application 1@eX_DigimatMF_JobManager, found URI PYRO:obj_9b862e3cd5c44a2f935c9c4c6c4bd5bd@172.30.0.112:9000 on ('172.30.0.112', 9000, 'None', 'None') from a nameServer <Pyro4.core.Proxy at 0x7f64160fa710; connected IPv4; for PYRO:Pyro.NameServer@172.30.0.1:9090> 

2020-01-14 10:14:56 INFO:PyroUtil.py:260 Connecting to application 1@eX_DigimatMF_JobManager with <Pyro4.core.Proxy at 0x7f641610ca90; not connected; for PYRO:obj_9b862e3cd5c44a2f935c9c4c6c4bd5bd@172.30.0.112:9000> 

2020-01-14 10:14:56 DEBUG:PyroUtil.py:262 Connected to DigimatApplication with the application 1@eX_DigimatMF_JobManager 

2020-01-14 10:14:56 INFO:A_2.py:102 Created digimat job 

2020-01-14 10:14:56 DEBUG:PyroUtil.py:597 Trying to connect to JobManager 

2020-01-14 10:14:57 INFO:PyroUtil.py:615 Allocated job, returned record from jobManager:(1, '21@MUL2.JobManager@UseCase1', 8917) 

2020-01-14 10:14:57 INFO:PyroUtil.py:638 Scenario: Connecting to 21@MUL2.JobManager@UseCase1 8917 

2020-01-14 10:14:57 DEBUG:PyroUtil.py:252 Application 21@MUL2.JobManager@UseCase1, found URI PYRO:obj_fd1905a1d7ab466498621cb02393ff29@172.30.0.172:8917 on ('172.30.0.172', 8917, 'None', 'None') from a nameServer <Pyro4.core.Proxy at 0x7f64160fa710; connected IPv4; for PYRO:Pyro.NameServer@172.30.0.1:9090> 

2020-01-14 10:14:57 INFO:PyroUtil.py:260 Connecting to application 21@MUL2.JobManager@UseCase1 with <Pyro4.core.Proxy at 0x7f641610cda0; not connected; for PYRO:obj_fd1905a1d7ab466498621cb02393ff29@172.30.0.172:8917> 

2020-01-14 10:14:57 DEBUG:PyroUtil.py:262 Connected to MUL2_FEM with the application 21@MUL2.JobManager@UseCase1 

2020-01-14 10:14:57 INFO:A_2.py:104 Created mul2 job 

2020-01-14 10:14:57 INFO:A_2.py:110 Working digimat solver on server DigimatApplication 

2020-01-14 10:14:57 INFO:A_2.py:112 Working mul2 solver on server MUL2_FEM 

2020-01-14 10:14:57 INFO:A_2.py:117 Metadata were successfully validate 

2020-01-14 10:14:57 INFO:A_2.py:128 Setting Execution Metadata of Digimat 

2020-01-14 10:14:57 INFO:A_2.py:129 Setting Execution Metadata of Mul2 

2020-01-14 10:14:58 DEBUG:Workflow.py:131 Step 1: t=1 dt=1 

2020-01-14 10:14:58 INFO:A_2.py:174 Running Digimat 

2020-01-14 10:15:00 INFO:A_2.py:235 Running Mul2 

2020-01-14 10:15:59 INFO:Model.py:558 RemoteApplication: Terminating jobManager job 1@eX_DigimatMF_JobManager on eX_DigimatMF_JobManager 

2020-01-14 10:16:00 INFO:Model.py:558 RemoteApplication: Terminating jobManager job 21@MUL2.JobManager@UseCase1 on MUL2.JobManager@UseCase1 

2020-01-14 10:16:00 INFO:Model.py:496 Terminating model 

2020-01-14 10:16:00 INFO:A_2.py:335 Requested KPI : Buckling Load: 10001.256 N 

2020-01-14 10:16:00 INFO:Model.py:496 Terminating model 

2020-01-14 10:16:00 INFO:A_2.py:337 Process complete 

